# Generated by Django 5.1.6 on 2025-07-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0005_delete_taggedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('tagged_user_email', models.EmailField(max_length=254)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
