# Generated by Django 5.1.6 on 2025-07-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0008_emailreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailreply',
            old_name='timestamp',
            new_name='sent_at',
        ),
    ]
