# Generated by Django 5.1.6 on 2025-07-08 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0010_email_taggedemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedemail',
            name='email',
        ),
        migrations.AddField(
            model_name='taggedemail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taggedemail',
            name='email_reply',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='gmail_app.emailreply'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taggedemail',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
