# Generated by Django 5.1.6 on 2025-07-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0011_remove_taggedemail_email_taggedemail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
