# Generated by Django 5.1.6 on 2025-07-09 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0012_alter_taggedemail_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.RemoveField(
            model_name='taggedemail',
            name='email_reply',
        ),
        migrations.RemoveField(
            model_name='taggedemail',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='taggedemail',
            name='tagged_user',
        ),
        migrations.AddField(
            model_name='emailreply',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='taggedemail',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='taggedemail',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taggedemail',
            name='sender_email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='taggedemail',
            name='subject',
            field=models.CharField(default='untitled', max_length=300),
        ),
        migrations.AddField(
            model_name='taggedemail',
            name='tagged_user_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailreply',
            name='sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailthread',
            name='created_at',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
