# Generated by Django 5.1.6 on 2025-07-10 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0013_delete_email_remove_taggedemail_email_reply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailreply',
            name='thread_id',
        ),
        migrations.AddField(
            model_name='emailreply',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='gmail_app.emailthread'),
        ),
        migrations.AddField(
            model_name='emailthread',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailthread',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailthread',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
