# Generated by Django 5.1.6 on 2025-07-12 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0018_chatmessage_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='gmail_app.emailthread'),
        ),
    ]
