# Generated by Django 5.1.6 on 2025-07-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0020_alter_chatmessage_thread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatNotification',
        ),
    ]
