# Generated by Django 5.1.6 on 2025-07-14 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0025_alter_chatnotification_thread_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='cleared_by',
            field=models.ManyToManyField(blank=True, related_name='cleared_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
